name: mobile_app_dev_ic9v2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.2.2
  path_provider: ^2.0.11
  path: ^1.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/cards/2_of_clubs.png
    - assets/cards/2_of_diamonds.png
    - assets/cards/2_of_hearts.png
    - assets/cards/2_of_spades.png
    - assets/cards/3_of_clubs.png
    - assets/cards/3_of_diamonds.png
    - assets/cards/3_of_hearts.png
    - assets/cards/3_of_spades.png
    - assets/cards/4_of_clubs.png
    - assets/cards/4_of_diamonds.png
    - assets/cards/4_of_hearts.png
    - assets/cards/4_of_spades.png
    - assets/cards/5_of_clubs.png
    - assets/cards/5_of_diamonds.png
    - assets/cards/5_of_hearts.png
    - assets/cards/5_of_spades.png
    - assets/cards/6_of_clubs.png
    - assets/cards/6_of_diamonds.png
    - assets/cards/6_of_hearts.png
    - assets/cards/6_of_spades.png
    - assets/cards/7_of_clubs.png
    - assets/cards/7_of_diamonds.png
    - assets/cards/7_of_hearts.png
    - assets/cards/7_of_spades.png
    - assets/cards/8_of_clubs.png
    - assets/cards/8_of_diamonds.png
    - assets/cards/8_of_hearts.png
    - assets/cards/8_of_spades.png
    - assets/cards/9_of_clubs.png
    - assets/cards/9_of_diamonds.png
    - assets/cards/9_of_hearts.png
    - assets/cards/9_of_spades.png
    - assets/cards/10_of_clubs.png
    - assets/cards/10_of_diamonds.png
    - assets/cards/10_of_hearts.png
    - assets/cards/10_of_spades.png
    - assets/cards/jack_of_clubs.png
    - assets/cards/jack_of_diamonds.png
    - assets/cards/jack_of_hearts.png
    - assets/cards/jack_of_spades.png
    - assets/cards/queen_of_clubs.png
    - assets/cards/queen_of_diamonds.png
    - assets/cards/queen_of_hearts.png
    - assets/cards/queen_of_spades.png
    - assets/cards/king_of_clubs.png
    - assets/cards/king_of_diamonds.png
    - assets/cards/king_of_hearts.png
    - assets/cards/king_of_spades.png
    - assets/cards/ace_of_clubs.png
    - assets/cards/ace_of_diamonds.png
    - assets/cards/ace_of_hearts.png
    - assets/cards/ace_of_spades.png

